# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: youngestar-backyard # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  Youngestar's backyard # ç½‘ç«™çš„æ ‡é¢˜
  description: Youngestar çš„ä¸ªäººåšå®¢, å¸Œæœ›æ˜¯ä¸€ä¸ªé™æ‚„æ‚„ä½†æœ‰æ„æ€çš„åœ°æ–¹ğŸŒ» # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: ä¸»é¡µ # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: åšå®¢
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: å…¨éƒ¨
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: æŠ€æœ¯æ€è€ƒ
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: ç”Ÿæ´»è®°å½•
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: friend
      text: å‹é“¾
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: message
      text: ç•™è¨€
      href: /message
      svg: "material-symbols:attach-email-outline-rounded"

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: Youngestar # ç”¨æˆ·å
  site: "https://youngestar.vercel.app/" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /avatar.jpg # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://github.com/youngestar"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://x.com/sing_a_giao"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://github.com/youngestar" # é“¾æ¥
        ariaLabel: Github # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: Github
        svg: "ri:github-line" # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
      - href: "https://x.com/sing_a_giao"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
